export enum FEATURE_SLUGS {
    HOSPITAL_MANAGEMENT = 'HOSPITAL_MANAGEMENT',
    PROVIDER_MANAGEMENT = 'PROVIDER_MANAGEMENT',
    PATIENT_MANAGEMENT = 'PATIENT_MANAGEMENT',
    DEPARTMENTS = 'DEPARTMENTS',
    TREATMENTS = 'TREATMENTS',
    ASSESMENTS = 'ASSESMENTS',
    HEALTH_TRACKER = 'HEALTH_TRACKER',
    CHRONIC_DISEAS = 'CHRONIC_DISEAS',
}