export enum PATIENTS_TAB {
    VITALS = 'VITALS',
    MEDICAL_CONDITIONS = 'MEDICAL_CONDITIONS',
    ASSESSMENT = 'ASSESSMENT',
    PATIENT_SUMMARY = 'PATIENT_SUMMARY',
    CALL_LOGS = 'CALL_LOGS',
    MONTHLY_CARE_REPORT = 'MONTHLY_CARE_REPORT',
    AWV = 'AWV',
    SELF_MANAGEMENT_PLAN = 'SELF_MANAGEMENT_PLAN',
    GENERAL_NOTES ='GENERAL_NOTES'
}